### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException - Caused by kotlin.UninitializedPropertyAccessException

### ISSUE THREAD

**Issue by khanhnt3010** [refiner-io/mobile-sdk-flutter#9]
I got Fatal Exception:
```
      Caused by kotlin.UninitializedPropertyAccessException: lateinit property koinApp has not been initialized
       at io.refiner.shared.LibKoinContext.getKoinApp(Koin.kt:27)
       at io.refiner.ui.q.invoke(SourceFile:1)
       at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
       at io.refiner.ui.RefinerSurveyFragment.getViewModel(SourceFile:1)
       at io.refiner.ui.RefinerSurveyFragment.onCreate(SourceFile:11)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:3090)
       at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:257)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
       at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2884)
       at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:252)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:220)
       at io.refiner.ui.RefinerSurveyActivity.onCreate(SourceFile:1)
       at android.app.Activity.performCreate(Activity.java:8591)
       at android.app.Activity.performCreate(Activity.java:8570)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4150)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4325)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8762)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

version: 1.3.6
Device: Galaxy S21 FE 5G

**Comment by tekinalper** [comment]
Obsolete issue.
